name: Sync Website to AWS S3

on:
  push:
    branches:
      - main

jobs:
  s3-sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ca-central-1

      - name: Sync files to S3 bucket
        run: |
          aws s3 sync . s3://ruelsinha.com --delete \
            --exclude ".git/*" \
            --exclude ".github/*" \
            --exclude ".vscode/*"